on:
  - push
  - pull_request

name: Continuous integration

jobs:
  example-policy-tests:
    name: Test suite of example policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      - run: dotnet test example/MyFirstKubewardenPolicy.Tests

  example-policy-e2e-tests:
    name: Run e2e tests of the example policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@a97c0700ad65b276f15fda9195937bb0db850dcf # v4.6.4
      - name: Run e2e tests
        run: |
          cd example/MyFirstKubewardenPolicy
          make e2e-tests
          