on:
  - push
  - pull_request

name: Continuous integration

jobs:
  example-policy-tests:
    name: Test suite of example policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      - run: dotnet test example/MyFirstKubewardenPolicy.Tests

  example-policy-e2e-tests:
    name: Run e2e tests of the example policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@f1695ca9a575bf58b85d6c3652c7ff7d1d12ec24 # v4.5.16
      - name: Run e2e tests
        run: |
          cd example/MyFirstKubewardenPolicy
          make e2e-tests
          