on:
  - push
  - pull_request

name: Continuous integration

jobs:
  example-policy-tests:
    name: Test suite of example policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      - run: dotnet test example/MyFirstKubewardenPolicy.Tests

  example-policy-e2e-tests:
    name: Run e2e tests of the example policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@143b9e4b11ddc47370482267383586e6f1bc7efe # v7.0.1
      - name: Run e2e tests
        run: |
          cd example/MyFirstKubewardenPolicy
          make e2e-tests
          